### ISSUE TITLE
Repository not found - error output is voluminous but not helpful

### ISSUE THREAD

**Issue by mc0e** [rodjek/librarian-puppet#101]
The info below is bad both because it exposes the user to a large stack trace, and also because the output doesn't actually identify the issue.  Which repository wasn't found?

I was able to get what I needed using the --debug command line option, (with even more voluminous info about software internals that shouldn't need to be exposed).

<code>
$ librarian-puppet update
/var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/source/git/repository.rb:201:in `block in run_command_internal': fatal: remote error:  (StandardError)
  Repository not found.
	from /usr/lib/ruby/1.9.1/open3.rb:208:in `popen_run'
	from /usr/lib/ruby/1.9.1/open3.rb:90:in `popen3'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/source/git/repository.rb:200:in `run_command_internal'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/source/git/repository.rb:152:in `block (2 levels) in run!'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/source/git/repository.rb:184:in `logging_command'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/source/git/repository.rb:151:in `block in run!'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/source/git/repository.rb:159:in `block (2 levels) in maybe_within'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/source/git/repository.rb:169:in `with_env_var'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/source/git/repository.rb:159:in `block in maybe_within'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/source/git/repository.rb:159:in `chdir'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/source/git/repository.rb:159:in `maybe_within'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/source/git/repository.rb:150:in `run!'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/source/git/repository.rb:71:in `clone!'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/source/git.rb:103:in `cache!'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/lib/librarian/puppet/source/git.rb:65:in `cache!'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/lib/librarian/puppet/source/git.rb:96:in `fetch_version'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/manifest.rb:109:in `fetch_version!'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/manifest.rb:101:in `fetched_version'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/manifest.rb:55:in `version'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/manifest.rb:85:in `satisfies?'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/dependency.rb:65:in `satisfied_by?'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:65:in `block (5 levels) in recursive_resolve'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:65:in `each'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:65:in `all?'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:65:in `block (4 levels) in recursive_resolve'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:103:in `scope'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:64:in `block (3 levels) in recursive_resolve'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:60:in `each'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:60:in `block (2 levels) in recursive_resolve'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:103:in `scope'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:59:in `block in recursive_resolve'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:103:in `scope'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:42:in `recursive_resolve'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:72:in `block (4 levels) in recursive_resolve'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:103:in `scope'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:64:in `block (3 levels) in recursive_resolve'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:60:in `each'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:60:in `block (2 levels) in recursive_resolve'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:103:in `scope'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:59:in `block in recursive_resolve'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:103:in `scope'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:42:in `recursive_resolve'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:72:in `block (4 levels) in recursive_resolve'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:103:in `scope'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:64:in `block (3 levels) in recursive_resolve'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:60:in `each'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:60:in `block (2 levels) in recursive_resolve'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:103:in `scope'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:59:in `block in recursive_resolve'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:103:in `scope'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:42:in `recursive_resolve'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:72:in `block (4 levels) in recursive_resolve'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:103:in `scope'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:64:in `block (3 levels) in recursive_resolve'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:60:in `each'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:60:in `block (2 levels) in recursive_resolve'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:103:in `scope'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:59:in `block in recursive_resolve'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:103:in `scope'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:42:in `recursive_resolve'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:72:in `block (4 levels) in recursive_resolve'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:103:in `scope'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:64:in `block (3 levels) in recursive_resolve'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:60:in `each'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:60:in `block (2 levels) in recursive_resolve'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:103:in `scope'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:59:in `block in recursive_resolve'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:103:in `scope'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:42:in `recursive_resolve'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:72:in `block (4 levels) in recursive_resolve'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:103:in `scope'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:64:in `block (3 levels) in recursive_resolve'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:60:in `each'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:60:in `block (2 levels) in recursive_resolve'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:103:in `scope'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:59:in `block in recursive_resolve'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:103:in `scope'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:42:in `recursive_resolve'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:72:in `block (4 levels) in recursive_resolve'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:103:in `scope'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:64:in `block (3 levels) in recursive_resolve'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:60:in `each'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:60:in `block (2 levels) in recursive_resolve'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:103:in `scope'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:59:in `block in recursive_resolve'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:103:in `scope'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:42:in `recursive_resolve'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:72:in `block (4 levels) in recursive_resolve'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:103:in `scope'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:64:in `block (3 levels) in recursive_resolve'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:60:in `each'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:60:in `block (2 levels) in recursive_resolve'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:103:in `scope'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:59:in `block in recursive_resolve'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:103:in `scope'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:42:in `recursive_resolve'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver/implementation.rb:20:in `resolve'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/resolver.rb:18:in `resolve'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/action/resolve.rb:25:in `run'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/cli.rb:161:in `resolve!'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/cli.rb:103:in `update'
	from /var/lib/gems/1.9.1/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/1.9.1/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
	from /var/lib/gems/1.9.1/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
	from /var/lib/gems/1.9.1/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/vendor/librarian/lib/librarian/cli.rb:29:in `bin!'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-0.9.9/bin/librarian-puppet:9:in `<top (required)>'
	from /usr/local/bin/librarian-puppet:19:in `load'
	from /usr/local/bin/librarian-puppet:19:in `<main>'
</code>

**Comment by carlossg** [comment]
I don't think this applies anymore
