### ISSUE TITLE
librarian-puppet and local forge with pulp

### ISSUE THREAD

**Issue by sliranc-zz** [rodjek/librarian-puppet#186]
Hello,

i am trying to use librarian-puppet with local forge installed using pulp extension for puppet.

While using local forge in my Puppetfile i am getting the following error: 

/usr/lib/ruby/gems/1.8/gems/librarian-puppet-0.9.14/lib/librarian/puppet/source/forge.rb:186:in `api_call': Error requesting http://.:puppet-modules@localhost/api/v1/releases.json?module=puppetlabs/mysql: 401 Unauthorized (OpenURI::HTTPError)

BTW puppet module install is working with the my local forge. 

The reason for the failure is related to the fact that the pulp use the url user and password for tagging the repository ID or consumer_id (because of some limitation with puppet module tool for puppet forge - you can read about this in https://pulp-puppet-user-guide.readthedocs.org/en/pulp-2.3/recipes.html).

To fix this you can add basic auth in the ruby open-uri 
/usr/lib/ruby/gems/1.8/gems/librarian-puppet-0.9.14/lib/librarian/puppet/source/forge.rb
line 179:
-data = open(url) {|f| f.read}
+data = open(url , :http_basic_authentication=>[user, password]) {|f| f.read}

the user should be the consumer_id and the password should be the repository_id this can be parsed from the url forge 
'http://liranc:puppet-modules@localhost'
consumer_id = liranc
repository_id = puppet-modules

i am using cents 6.5 with ruby version 1.8.7 
gem list 
librarian (0.1.2)
librarian-puppet (0.9.14)

Regards
LiranC

**Comment by lastmikoi** [comment]
This issue is affecting my deployment as well, but I wasn't able to use sliranc's workaround.

Indeed, I'm getting this exception ```~/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/open-uri.rb:254:in `open_http': userinfo not supported.  [RFC3986] (ArgumentError)"``` when using the following forge URL : `https://consumer_id:repository_id@forge.domain.tld/`

I'm using librarian-puppet (2.1.0) and ruby-1.9.3-p551, and defining `consumer_id` and `repository_id` is the only way to make librarian-puppet work with my pulp selft-hosted forge.
