### ISSUE TITLE
Update to use forgeapi.puppetlabs.com and API v3

### ISSUE THREAD

**Issue by domcleal** [rodjek/librarian-puppet#210]
I'm running librarian-puppet 1.0.1 and Puppet 3.6.0-rc1 (the git tag, currently unreleased), but am hitting problems with the migration from forge.puppetlabs.com to forgeapi.puppetlabs.com, and the v1 to v3 API switch.
1. In the same vein as bd29b9fb, the client_api_version method should return v3 for Puppet 3.6 or higher.
2. Changing the Forge URL in Puppetfile to https://forgeapi.puppetlabs.com fails too, as librarian-puppet tries to query `https://forgeapi.puppetlabs.com/api/v1/releases.json?module=puppetlabs/mysql`.  The /api prefix needs removing.

Any thoughts on the best way to implement part (2)?  Forcing users to add /api to their existing Forge URLs would be incompatible, so perhaps detecting the URL is best and then adding/removing /api as applicable...  Or perhaps if Puppet Labs redirected /api to / on forgeapi.pl.com, compatibility could be maintained and in future, the path should be added to the Forge URL in the Puppetfile.  (@ryanycoleman)

**Comment by mfowlewebs** [comment]
Is there any reason to stay on v1? Should v3 be made the default at some point, and when would be the time to consider that change?
