### ISSUE TITLE
librarian-puppet returns "Unable to find module" on puppet forge

### ISSUE THREAD

**Issue by pantala** [rodjek/librarian-puppet#236]
Environment: Windows 8, Ruby 1.9.3, librarian-puppet 1.1.2, librarian 0.1.2.

Example puppetfile:

    forge "http://forge.puppetlabs.com"
    mod 'jonono/php',         :git => 'https://github.com/jonono/puppet-php.git', :ref => '0.1.4'
    mod 'jonono/syslogng',    :git => 'https://github.com/jonono/puppet-syslogng', :ref => '0.1.0' 
    mod 'simondean/iis',      '0.1.3'

In this case `jonono/php` and `jonono/syslogng` install fine, however librarian-puppet returns 

    Unable to find module 'simondean/iis' on https://forgeapi.puppetlabs.com

This occurs for any module that doesn't have a specific repo reference. Here's the --verbose output after the above error: https://gist.github.com/pantala/b40edeca743f357b5517

Help?

**Comment by mc0e** [comment]
I'm seeing the same issue, on Ubuntu Linux.  When using the forge url as provided by init, I get a 301 redirect.  I.e. ` http://forge.puppetlabs.com/v3/releases?module=puppetlabs-stdlib` redirects to `https://forge.puppetlabs.com/v3/releases?module=puppetlabs-stdlib`

If I change the forge URL in the Puppetfile to https though, the module isn't found:

    mc0e@laptop$ librarian-puppet install --verbose
    [Librarian] Ruby Version: 1.9.3
    [Librarian] Ruby Platform: x86_64-linux
    [Librarian] Rubygems Version: 1.8.23
    [Librarian] Librarian Version: 0.1.1
    [Librarian] Librarian Adapter: puppet
    [Librarian] Librarian Adapter Version: 0.9.10
    [Librarian] Project: /home/mc0e/tmp/test-plib
    [Librarian] Specfile: Puppetfile
    [Librarian] Lockfile: Puppetfile.lock
    [Librarian] Git: /usr/bin/git
    [Librarian] Git Version: 1.9.1
    [Librarian] Git Environment Variables:
    [Librarian]   (empty)
    [Librarian] Pre-Cached Sources:
    [Librarian] Post-Cached Sources:
    [Librarian]   [:forge, "https://forge.puppetlabs.com", {}]
    [Librarian] Scheduling puppetlabs/stdlib (>= 0) <https://forge.puppetlabs.com>
    [Librarian] Resolving puppetlabs/stdlib (>= 0) <https://forge.puppetlabs.com>
    [Librarian]   Checking manifests
    Unable to find module 'puppetlabs/stdlib' on https://forge.puppetlabs.com
    /usr/lib/ruby/vendor_ruby/librarian/puppet/source/forge.rb:22:in `versions'
    /usr/lib/ruby/vendor_ruby/librarian/puppet/source/forge.rb:34:in `manifests'
    /usr/lib/ruby/vendor_ruby/librarian/puppet/source/forge.rb:274:in `manifests'
    /usr/lib/ruby/vendor_ruby/librarian/dependency.rb:113:in `cache_manifests!'
    /usr/lib/ruby/vendor_ruby/librarian/dependency.rb:109:in `manifests'
    /usr/lib/ruby/vendor_ruby/librarian/resolver/implementation.rb:141:in `block in resolving_dependency_map_find_manifests'
    /usr/lib/ruby/vendor_ruby/librarian/resolver/implementation.rb:154:in `block (2 levels) in scope_resolving_dependency'
    /usr/lib/ruby/vendor_ruby/librarian/resolver/implementation.rb:168:in `block in scope_checking_manifests'
    /usr/lib/ruby/vendor_ruby/librarian/resolver/implementation.rb:208:in `scope'
    /usr/lib/ruby/vendor_ruby/librarian/resolver/implementation.rb:167:in `scope_checking_manifests'
    /usr/lib/ruby/vendor_ruby/librarian/resolver/implementation.rb:153:in `block in scope_resolving_dependency'
    /usr/lib/ruby/vendor_ruby/librarian/resolver/implementation.rb:208:in `scope'
    /usr/lib/ruby/vendor_ruby/librarian/resolver/implementation.rb:152:in `scope_resolving_dependency'
    /usr/lib/ruby/vendor_ruby/librarian/resolver/implementation.rb:140:in `resolving_dependency_map_find_manifests'
    /usr/lib/ruby/vendor_ruby/librarian/resolver/implementation.rb:56:in `recursive_resolve'
    /usr/lib/ruby/vendor_ruby/librarian/resolver/implementation.rb:32:in `resolve'
    /usr/lib/ruby/vendor_ruby/librarian/resolver.rb:16:in `resolve'
    /usr/lib/ruby/vendor_ruby/librarian/action/resolve.rb:26:in `run'
    /usr/lib/ruby/vendor_ruby/librarian/cli.rb:169:in `resolve!'
    /usr/lib/ruby/vendor_ruby/librarian/puppet/cli.rb:63:in `install'
    /usr/lib/ruby/vendor_ruby/thor/command.rb:27:in `run'
    /usr/lib/ruby/vendor_ruby/thor/invocation.rb:121:in `invoke_command'
    /usr/lib/ruby/vendor_ruby/thor.rb:363:in `dispatch'
    /usr/lib/ruby/vendor_ruby/thor/base.rb:440:in `start'
    /usr/lib/ruby/vendor_ruby/librarian/cli.rb:26:in `block (2 levels) in bin!'
    /usr/lib/ruby/vendor_ruby/librarian/cli.rb:31:in `returning_status'
    /usr/lib/ruby/vendor_ruby/librarian/cli.rb:26:in `block in bin!'
    /usr/lib/ruby/vendor_ruby/librarian/cli.rb:47:in `with_environment'
    /usr/lib/ruby/vendor_ruby/librarian/cli.rb:26:in `bin!'
    /usr/bin/librarian-puppet:9:in `<main>'

**Comment by feniix** [comment]
You are using the package provided by ubuntu, if you install librarian using `gem install librarian-puppet` and remove the package `apt-get remove --purge librarian-puppet` you will see your problem fixed.

**Comment by carlossg** [comment]
Seems to me that you are all running old versions of librarian-puppet. Update to latest and reopen if it doesn't work. 
The `Librarian Adapter Version` in debug log should be 1.4.1 or 2.0.1

**Comment by mc0e** [comment]
I've now got the gem version, and it's working.

I've created a bug report against the ubuntu package.

https://bugs.launchpad.net/ubuntu/+source/librarian-puppet/+bug/1417620
