### ISSUE TITLE
Path names are too long for windows

### ISSUE THREAD

**Issue by petehayes** [rodjek/librarian-puppet#256]
I am running into the Windows 260 character limit for file paths.  The .tmp structure is highly nested and ends up generating paths beyond the limit.  The file the library trips up on is:

c:/ws/vm-prpc-ready-rh65-pg91-tc7-j7/puppet/.tmp/librarian/cache/source/puppet/forge/forgeapi_puppetlabs_com/puppetlabs-postgresql/4.0.0/cache/tmp-unpacker20140922-7768-h352q1/puppetlabs-postgresql-4.0.0/spec/unit/functions/postgresql_acls_to_resources_hash_spec.rb

Can the path be shortened some to avoid this issue?

**Comment by webcoderio** [comment]
Man, this issue drove me for at least 4 hours until I found out windows complaining the path is too long...
Why this is not getting fixed? .tmp should just move out from the current path of puppet...
