### ISSUE TITLE
Version 1.0.3 no longer installs due to highline dependency

### ISSUE THREAD

**Issue by bbranan** [rodjek/librarian-puppet#286]
As of yesterday (02/25/2015) attempts to install librarian puppet version 1.0.3 fail with a message indicating that the highline dependency requires Ruby version 1.9.3 or greater. I am using the default Ruby version on Ubuntu 12.04.5, which is version 1.8.7.

It appears that highline generated a new release (version 1.7.1) on Feb 24, 2015 at 7:58pm ET (https://github.com/JEG2/highline/releases) which now requires Ruby version 1.9.3. Version 1.0.3 of librarian-puppet appears to be picking up this latest version of highline, and thus generating the noted error.

I am able to resolve the issue by installing version 1.6.1 of the highline gem prior to installing librarian-puppet. Would it be possible to require version 1.6.1 of highline specifically in the 1.0.x line of librarian-puppet? This would allow those of us still stuck on the 1.8.x version of Ruby to continue to use librarian-puppet without needing to first install a seemingly unrelated gem.

Thanks!

**Comment by carlossg** [comment]
Just install a previous version of highline as you did. It is actually not needed and is removed in the next version (already committed in master) when using the new `librarianp` gem
