### ISSUE TITLE
stdlib install causes Puppetfile and Puppetfile.lock are out of sync!

### ISSUE THREAD

**Issue by savithari** [rodjek/librarian-puppet#292]
Friends:

We are facing the issue of the error Puppetfile and Puppetfile.lock are out of sync! when trying to install stdlib.

============================
Puppet File contents:

```
forge "https://forgeapi.puppetlabs.com"

mod 'stdlib',
	:git => 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
```

Puppetfile.lock file contents
```
GIT
  remote: https://github.com/puppetlabs/puppetlabs-stdlib.git
  ref: master
  sha: 59b3fb4472c6ceafc6762739e767294054787bd4
  specs:
    stdlib (4.5.1)

DEPENDENCIES
  stdlib (>= 0)
```
=============================================
Kindly help.

Thank You for your time and attention.

Regards,
-N

**Comment by carlossg** [comment]
versions and output? https://github.com/rodjek/librarian-puppet#reporting-issues

**Comment by savithari** [comment]
Oops.  I thought I put that in.
Ruby Version:
```
ROSELCDV0080787:vagrantStuff nlakshmi$ ruby --version
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin13]
```
Librarian puppet version
```
~/.gems/ruby/2.0.0/gems/librarian-puppet-2.1.0/bin/librarian-puppet -version
librarian-puppet v2.1.0
```
![librarian-puppet](https://cloud.githubusercontent.com/assets/310790/7158819/973ef83a-e34b-11e4-9e8c-5784bb8027bd.png)

**Comment by savithari** [comment]
Can I get some help please ?  I tried various versions of librarian-puppet but same issues.

-N

**Comment by carlossg** [comment]
works fine here, try deleting the .lock file
