### ISSUE TITLE
Lack of documentation?

### ISSUE THREAD

**Issue by jearls** [rodjek/librarian-puppet#295]
I apologize in advance.  I'm a bit frustrated and that comes out below.  I'm trying to tone it down.

This is a request for more complete documentation.

For having such widespread use and acclaim, I was surprised at holes in the documentation for this tool.

Some examples:

You give an abbreviated list of two options, `--clean` and `--verbose`, for the `librarian-puppet install` command, but don't describe what `--clean` means.  Running `librarian-puppet help install` lists a whole bunch of options without saying what any of them mean.

You have a whole long section on "Configuration" and only end up describing two configuration options, `path` and `tmp`.  Are there only two configuration options for the entire system?  Also, the description for the `path` configuration option talks about "cookbooks".  What are cookbooks?  That's the first and only time that "cookbooks" ever mentioned in the entire document.

There's other places where the documentation only makes sense if you already know what it's talking about.  For example, the only reference to the `metadata` directive is a backwards reference to a previous description of the default behavior in the absence of a Puppetfile.  My first few times reading this document, I completely missed that back-reference and kept looking for the section that would explain what the `metadata` directive did.

**Comment by carlossg** [comment]
I have fixed a couple of things in the readme, a PR with improved docs would always be welcome
