### ISSUE TITLE
Metadata file does not exist: /etc/puppet/environments/production/metadata.json

### ISSUE THREAD

**Issue by robbyt** [rodjek/librarian-puppet#299]
With this really basic Puppetfile, I'm getting the error "Metadata file does not exist" when I run:

`cd /etc/puppet/environments/production ; librarian-puppet install --destructive`

I'm running Ubuntu 14.04, Puppet 3.7.5, Ruby 1.9.3p484. 

Can I safely ignore this error? What am I doing wrong?

```ruby
#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"

# use dependencies defined in metadata.json
metadata

mod 'puppetlabs-stdlib', '4.6.0'
mod 'puppetlabs-apache', '1.4.1'
```

**Comment by carlossg** [comment]
you are using `metadata` which says "use dependencies defined in metadata.json" and you don't have a metadata.json?

**Comment by robbyt** [comment]
@carlossg I was confused by the documentation for `metadata`, I thought that this was to tell librarian-puppet to read the `metadata.json` files inside of the modules instead of the `Modulefile`.

What is the actual usecase for the `metadata` option? Is using it like an alternative to listing the modules in the Puppetfile?

**Comment by carlossg** [comment]
correct, so you don't need to duplicate info
