### ISSUE TITLE
gitignore modules

### ISSUE THREAD

**Issue by habitullence** [rodjek/librarian-puppet#300]
Why is modules added to .gitignore?

**Comment by robbyt** [comment]
Because once you start using librarian-puppet, the modules directory is 100% managed by librarian-puppet and should not be committed to source control.

**Comment by habitullence** [comment]
Is it actually specific to each machine though? For example, it used to be best practice not to commit the vendor directory with Bundler, and while I like the commit everything you need to build the project practice, it's a hell of a lot faster to build once rather than on each deploy.

**Comment by robbyt** [comment]
You can always just remove the .gitignore file and do this :)

**Comment by habitullence** [comment]
How can I delete it? j/k Guess I'll add to git and see if anything breaks when provisioning unless @rodjek has any input.

**Comment by carlossg** [comment]
Just edit the .gitignore if you want to commit the modules. I don't recommend it but it is up to you
