### ISSUE TITLE
question:  how to get list of resolved dependencies from API

### ISSUE THREAD

**Issue by logicminds** [rodjek/librarian-puppet#301]
@carlossg How can I use puppet-librarian to return a ruby object that contains all the resolved dependencies?  I am looking to use this in a downstream project that would produce a .fixtures.yml file of dependencies for rspec-puppet testing.  I don't need puppet-librarian for anything else though since puppetlabs-spec-helper handles downloading fixtures.  But since puppet-librarian consults Puppetfile, modulefile, and metadata.json it seems like this is the easiest approach.

**Comment by carlossg** [comment]
it should be possible, but what I've done in the past is running librarian-puppet just before rspec-puppet
https://github.com/maestrodev/puppet-rvm/blob/master/Rakefile#L14

the fixtures file didn't support both git and forge sources

**Comment by logicminds** [comment]
Well I am only looking to use the resolve method to produce a ruby object of dependencies programmatically.  It seeems like I just want to run this command.

https://github.com/rodjek/librarian-puppet/blob/master/lib/librarian/puppet/cli.rb#L103

Although I am not sure the context of the environment and options arguments are.  

Can I just call `Action::Resolve.new(environment, options).run` directly?

**Comment by carlossg** [comment]
I think you should be able.
environment is Librarian::Puppet::Environment, options is just a hash

The parent class is at https://github.com/carlossg/librarian/blob/librarianp/lib/librarian/cli.rb

**Comment by carlossg** [comment]
The receiver_spec in branch `issue-302` should be what you need, will merge as soon as travis tests pass
