### ISSUE TITLE
Caching modules?

### ISSUE THREAD

**Issue by amos-stan** [rodjek/librarian-puppet#308]
It will be great to be able to cache modules access by librarian-puppet.

My scenario is that I run librarian-puppet as part of a TeamCity + Vagrant + Puppet provision plan to verify my changes. 99% of the time librarian-puppet will download the same modules.
The TeamCity job runs from a clean slate so it can't take advantage of librarian-puppet's .tmp directory.

It will be nice to be able to help speed things up by providing an external cache.

**Comment by carlossg** [comment]
https://github.com/rodjek/librarian-puppet

    The tmp config sets the cache directory for librarian. If a relative path, it is relative to the directory containing the Puppetfile. The equivalent environment variable is LIBRARIAN_PUPPET_TMP.
