### ISSUE TITLE
Should not resolve to deleted versions of modules

### ISSUE THREAD

**Issue by maxstepanov** [rodjek/librarian-puppet#310]
Puppet modules can be deleted from forge.
librarian-puppet doesn't respect that and resolves to non existent version.
Here is an example that i have a problem with.
```
    {
      "uri": "/v3/releases/puppetlabs-concat-2.0.1",
      "slug": "puppetlabs-concat-2.0.1",
      "version": "2.0.1",
      "supported": false,
      "created_at": "2015-06-02 13:27:28 -0700",
      "deleted_at": "2015-06-12 11:12:51 -0700"
    }
```
Versions with ``deleted_at`` not ``null`` should be skipped.

**Comment by tedivm** [comment]
:+1: 

Now that the puppetlabs people have removed the concat 2.0.x line of code this is a serious bug that is going to break a lot of people. Although the work around is easy (require version "< 2.0.0" on the main puppetfile) it's still a pretty jarring bug.
