### ISSUE TITLE
Remove puppet as a dependency

### ISSUE THREAD

**Issue by brianhks** [rodjek/librarian-puppet#318]
First a little history.  I'm creating a setup where by I prepackage my environments.  Puppet masters then download on the fly the environment they need for a particular agent.  As a result I need to resolve/download dependencies at develop time instead of deploy time.  This has huge ramifications.

Anyway when using librarian-puppet to download modules dependencies it calls out to puppet (ew), to download the file and place it in the modules folder.  I've been able to replace the call to puppet with a curl statement and call to tar -xf.  I would like this to be a standard feature, just not sure how to go about doing it.

Thanks

**Comment by carlossg** [comment]
You need to change https://github.com/rodjek/librarian-puppet/blob/master/lib/librarian/puppet/source/forge/repo.rb#L110 and submit a PR

If all the test pass it should be ok to go

**Comment by brianhks** [comment]
I'll do a pull request with what I have, there may be a better way of doing things as I'm a pretty crappy ruby developer.

**Comment by carlossg** [comment]
handled in #321
