### ISSUE TITLE
verbose option not working with new git version

### ISSUE THREAD

**Issue by Fabian1976** [rodjek/librarian-puppet#343]
When trying to run `librarian-puppet` with the `--verbose` option, I get this output:
```
[Librarian] Git: /usr/bin/git
error: unknown option `silent'
usage: git version [<options>]

    --build-options       also print build options
```

When I run `git version`, I get this output:
```
git version 2.14.1
```

When I run `git version --silent`, I get the same error as the librarian-puppet run:
```
$ git version --silent
error: unknown option `silent'
usage: git version [<options>]

    --build-options       also print build options

```

**Comment by Fabian1976** [comment]
I've tested with git version 2.13.3 and that still works fine. So it seems the `--silent` was removed from git 2.14.x
```
$ git version --silent
git version 2.13.3
```

**Comment by carlossg** [comment]
Moved to https://github.com/voxpupuli/librarian-puppet
