### ISSUE TITLE
Need to ignore local changes for development environment (vagrant)

### ISSUE THREAD

**Issue by ytjohn** [rodjek/librarian-puppet#88]
We are not currently utilizing librarian, but I hope very much to do so.
We use vagrant to develop and test our modules. Essentially, the directory 
containing our modules is in the same directory as the Vagrantfile. 
`vagrant provision` applies the puppet manifests directly to the vagrant instance.
Ideally, we would like to have `vagrant provision` call `librarian update`.

Here is the main issue I am encountering - librarian overwrites the module directory.
I'll say that this is not an issue with librarian (librarian is working as
designed, just not as I would like).

Let's assume I need to add a new file to a module for testing.

		$ librarian-puppet update
		$ cd modules/ntp/
		$ touch newfile
		$ git add newfile
		$ git commit -m 'newfile test'
		1 file changed, 0 insertions(+), 0 deletions(-)
		create mode 100644 newfile
		$ cd ../..
		
I do my testing and run vagrant-provision which calls librarian-puppet. I see
that librarian is smart enough to detect my alterations to ntp and then overwrite it.

		$ librarian-puppet update --verbose
		[Librarian] Ruby Version: 1.8.7
		[Librarian] Ruby Platform: universal-darwin12.0
		[Librarian] Rubygems Version: 1.3.6
		[Librarian] Librarian Version: 0.0.24
		[Librarian] Librarian Adapter: puppet
		[Librarian] Project: /Users/jth21/devel/librarianfun/vagrants
		[Librarian] Specfile: Puppetfile
		[Librarian] Lockfile: Puppetfile.lock
		[Librarian] Git: /usr/local/bin/git
		[Librarian] Git Version: git version 1.8.2
		[Librarian] Git Environment Variables:
		[Librarian]   (empty)
		[Librarian] Pre-Cached Sources:
		[Librarian] Post-Cached Sources:
		[Librarian]   [:git, "git://github.com/puppetlabs/puppetlabs-ntp.git", {}]
		[Librarian]   [:forge, "http://forge.puppetlabs.com", {}]
		[Librarian] Scheduling ntp (>= 0) <git://github.com/puppetlabs/puppetlabs-ntp.git#master>
		[Librarian] Resolving ntp (>= 0) <git://github.com/puppetlabs/puppetlabs-ntp.git#master>
		[Librarian]   No known prior constraints
		[Librarian]   Checking manifests
		[Librarian] Running `/usr/local/bin/git reset --hard --quiet` in .tmp/librarian/cache/source/git/66076c171c9e7acc6a0341347cc866b2
		[Librarian]     --- No output
		[Librarian] Running `/usr/local/bin/git clean -x -d --force --force` in .tmp/librarian/cache/source/git/66076c171c9e7acc6a0341347cc866b2
		[Librarian]     --- No output
		[Librarian] Running `/usr/local/bin/git rev-parse HEAD --quiet` in .tmp/librarian/cache/source/git/66076c171c9e7acc6a0341347cc866b2
		[Librarian]     --> 99bae40f225db0dd052efbf1d4078a21f0333331
		[Librarian] Running `/usr/local/bin/git fetch origin --quiet` in .tmp/librarian/cache/source/git/66076c171c9e7acc6a0341347cc866b2
		[Librarian]     --- No output
		[Librarian] Running `/usr/local/bin/git fetch origin --quiet --tags` in .tmp/librarian/cache/source/git/66076c171c9e7acc6a0341347cc866b2
		[Librarian]     --- No output
		[Librarian] Running `/usr/local/bin/git remote` in .tmp/librarian/cache/source/git/66076c171c9e7acc6a0341347cc866b2
		[Librarian]     --> origin
		[Librarian] Running `/usr/local/bin/git branch -r` in .tmp/librarian/cache/source/git/66076c171c9e7acc6a0341347cc866b2
		[Librarian]     -->   origin/HEAD -> origin/master
		[Librarian]     -->   origin/contributing_guide
		[Librarian]     -->   origin/doh/nrosier/patch-1
		[Librarian]     -->   origin/master
		[Librarian]     -->   origin/readme_update
		[Librarian] Running `/usr/local/bin/git rev-parse origin/master^{commit} --quiet` in .tmp/librarian/cache/source/git/66076c171c9e7acc6a0341347cc866b2
		[Librarian]     --> 99bae40f225db0dd052efbf1d4078a21f0333331
		[Librarian] Running `/usr/local/bin/git rev-parse HEAD --quiet` in .tmp/librarian/cache/source/git/66076c171c9e7acc6a0341347cc866b2
		[Librarian]     --> 99bae40f225db0dd052efbf1d4078a21f0333331
		[Librarian] Running `/usr/local/bin/git rev-parse HEAD --quiet` in .tmp/librarian/cache/source/git/66076c171c9e7acc6a0341347cc866b2
		[Librarian]     --> 99bae40f225db0dd052efbf1d4078a21f0333331
		[Librarian]     Checking ntp/0.3.0 <git://github.com/puppetlabs/puppetlabs-ntp.git#master>
		[Librarian]       Scheduling puppetlabs/stdlib (>= 0.1.6) <http://forge.puppetlabs.com>
		[Librarian]       Resolving puppetlabs/stdlib (>= 0.1.6) <http://forge.puppetlabs.com>
		[Librarian]         No known prior constraints
		[Librarian]         Checking manifests
		[Librarian]           Checking puppetlabs/stdlib/3.2.0 <http://forge.puppetlabs.com>
		[Librarian]             Resolved puppetlabs/stdlib (>= 0.1.6) <http://forge.puppetlabs.com> at puppetlabs/stdlib/3.2.0 <http://forge.puppetlabs.com>
		[Librarian]         Resolved puppetlabs/stdlib (>= 0.1.6) <http://forge.puppetlabs.com>
		[Librarian]       Resolved ntp (>= 0) <git://github.com/puppetlabs/puppetlabs-ntp.git#master> at ntp/0.3.0 <git://github.com/puppetlabs/puppetlabs-ntp.git#master>
		[Librarian]   Resolved ntp (>= 0) <git://github.com/puppetlabs/puppetlabs-ntp.git#master>
		[Librarian] Bouncing Puppetfile.lock
		[Librarian] Pre-Cached Sources:
		[Librarian] Post-Cached Sources:
		[Librarian]   [:git, "git://github.com/puppetlabs/puppetlabs-ntp.git", {}]
		[Librarian]   [:forge, "http://forge.puppetlabs.com", {}]
		[Librarian] Installing ntp/0.3.0 <git://github.com/puppetlabs/puppetlabs-ntp.git#master>
		[Librarian] Running `/usr/local/bin/git reset --hard --quiet` in .tmp/librarian/cache/source/git/66076c171c9e7acc6a0341347cc866b2
		[Librarian]     --- No output
		[Librarian] Running `/usr/local/bin/git clean -x -d --force --force` in .tmp/librarian/cache/source/git/66076c171c9e7acc6a0341347cc866b2
		[Librarian]     --- No output
		[Librarian] Running `/usr/local/bin/git rev-parse HEAD --quiet` in .tmp/librarian/cache/source/git/66076c171c9e7acc6a0341347cc866b2
		[Librarian]     --> 99bae40f225db0dd052efbf1d4078a21f0333331
		[Librarian] Deleting modules/ntp
		[Librarian] Copying .tmp/librarian/cache/source/git/66076c171c9e7acc6a0341347cc866b2 to modules/ntp
		
If I'm running a puppet server, this is exactly the behavior I want. When I'm developing
the modules locally, it's obviously counter-productive.

I could work-around this by developing my modules in another location, commit and
push my code for a round trip each time through the git server. However, this is pretty
inefficient. Or, I could just have a rule "don't run librarian-puppet until you really
mean it", but I'd really like to integrate this whole thing within `vagrant provision`.

I'm looking for a solution to make this work. Ideally, we would have a command - it could
be a wrapper around librarian-puppet, or a new flag/login in librarian-puppet to handle
the following logic:

1. If any module has local updates, do not touch.
2. If a module (without local changes) has a newer version available, update it.

Of course, I am open to any additional suggestions.

**Comment by carlossg** [comment]
The way it works, you should have a :path dependency and point it to the folder with the modified module, not using the `modules` folder
